# config.py
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# API Configuration
API_CONFIG = {
    "anthropic_api_key": os.getenv("ANTHROPIC_API_KEY"),
    "openai_api_key": os.getenv("OPENAI_API_KEY"),  # For Whisper speech-to-text
}

# Google Sheets Configuration
GOOGLE_SHEETS_CONFIG = {
    "spreadsheet_name": "AI Trading Journal",
    "credentials_file": "credentials.json",  # We'll create this
    "scopes": [
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/drive.file",
    ],
}

# Trading Journal Structure
JOURNAL_COLUMNS = [
    "Date",
    "Symbol",
    "Company_Name",  # Added this since Webull provides it
    "Entry_Price",
    "Entry_Time",
    "Exit_Price",
    "Exit_Time",
    "Quantity",
    "PnL_Dollar",  # We'll calculate this
    "PnL_Percent",  # We'll calculate this
    "Duration_Minutes",  # We'll calculate this
    "Entry_Reason",  # From voice input
    "Exit_Reason",  # From voice input
    "Emotional_State",  # From voice input
    "Market_Context",  # From voice input
    "Lessons_Learned",  # From voice input
    "AI_Analysis",  # Generated by Claude
    "Trade_Grade",  # A-F grade from AI
]

# Voice Processing Settings
VOICE_CONFIG = {
    "max_recording_duration": 120,  # 2 minutes max per trade explanation
    "sample_rate": 16000,  # Audio quality
    "chunk_duration": 1000,  # Process audio in 1-second chunks
    "silence_threshold": 500,  # Milliseconds of silence to stop recording
}

# CSV Parsing Configuration
CSV_CONFIG = {
    "webull_columns": {
        "symbol": "Symbol",
        "side": "Side",
        "quantity": "Filled",  # Use filled quantity, not total
        "price": "Avg Price",  # Use actual execution price
        "time": "Filled Time",  # Use fill time, not placed time
        "company_name": "Name",
        "status": "Status",
    },
    "timezone": "US/Eastern",
    "required_status": "Filled",  # Only process filled orders
    "time_format": "%m/%d/%Y %H:%M:%S %Z",  # Matches your format
}

# App Configuration
APP_CONFIG = {
    "page_title": "Voice Trading Journal",
    "page_icon": "🎤",
    "layout": "wide",
}
